### GET Expertises - Sectors - searchSectors - with existing sector
GET https://localhost:7001/api/Expertises/searchSectors?searchTerm=Tech
Accept: application/json

### GET Expertises - Sectors - searchSectors - with a non-existing sector
GET https://localhost:7001/api/Expertises/searchSectors?searchTerm=abc123
Accept: application/json

### GET Expertises - ExpertiseCategory - searchExpertiseCategories - with existing ExpertiseCategory
GET https://localhost:7001/api/Expertises/searchExpertiseCategories?searchTerm=.NET
Accept: application/json

### GET Expertises - ExpertiseCategory - searchExpertiseCategories - with a non-existing ExpertiseCategory
GET https://localhost:7001/api/Expertises/searchExpertiseCategories?searchTerm=abc123
Accept: application/json

### GET Expertises - Expertise - searchExpertises - with existing expertise
GET https://localhost:7001/api/Expertises/searchExpertises?searchTerm=General
Accept: application/json

### GET Expertises - Expertise - searchExpertises - with a non-existing expertise
GET https://localhost:7001/api/Expertises/searchExpertises?searchTerm=abc123
Accept: application/json
